### ISSUE TITLE
some passwords of mysql user generate an error launching the command the to finalize the upgrade  from 8.6.2 to 8.7.0

### ISSUE THREAD

**Issue by vincenzofrezza** [salesagility/SuiteCRM-Core#556] opened 2024-10-18 12:39 UTC
### Issue

Following instrutions here: [Upgrading to SuiteCRM 8.2.x+ versions :: SuiteCRM Documentation](https://docs.suitecrm.com/8.x/admin/upgrading/upgrading-82x-versions/) everything works fine untill the finalization command

`sudo ./bin/console suitecrm:app:upgrade-finalize -t SuiteCRM-8.7.0`

that returns this result:
`Running: legacy-post-upgrade
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
step: legacy-post-upgrade | status: done
Post Upgrade process complete
Running: add-new-config-entries
step: add-new-config-entries | status: done
No new entries to add to the config file
Running: metadata-merge
step: metadata-merge | status: done
Metadata successfully merged
Running: run-migrations

In App_KernelProdContainer.php line 2089:

You have requested a non-existent parameter “23W”.

suitecrm:app:upgrade-finalize [-t|–target-version TARGET-VERSION] [-m|–metadata-merge [METADATA-MERGE]]`

Keep in mind that the password of the user that access to mysql db contains "%23%" !

I am runninng on an ubuntu machine with:
Apache 2.4.52 and PHP 8.1.2

### Possible Fix

I changed the password as suggested in the suitecrm community ...and the prosess worked smoothly. So the password is really the problem.

### Steps to Reproduce the Issue

```bash
1. start from susitecrm 8.6.2
2. follows steps yu can find
3. https://docs.suitecrm.com/8.x/admin/upgrading/upgrading-82x-versions/
...
```

### Context

Impossible to terminate the upgrade

### Version

8.6.2

### What browser are you currently using?

Firefox

### Browser Version

131.03

### Environment Information

 Apache 2.4.52 and PHP 8.1.2

### Operating System and Version

Ubuntu 22.04.3 LTS

**Comment by johnM2401** [comment] 2024-10-18 16:12
Hey!
Thank you for getting in touch and raising this.

For future reference, I think this is likely a duplicate of: https://github.com/salesagility/SuiteCRM-Core/issues/553
(However, if you feel otherwise, please let me know!)

Thank you again!

**Comment by mattlorimer** [comment] 2024-12-05 10:56
Closed as duplicate of https://github.com/salesagility/SuiteCRM-Core/issues/553

**Closed by mattlorimer** 2024-12-05 10:56 UTC
Labels: Type: Bug, Type:Duplicate, Priority:Important, Area: Installation, Severity: Major
