### ISSUE TITLE
status value missing in user form

### ISSUE THREAD

**Issue by f1-outsourcing** [salesagility/SuiteCRM-Core#124] opened 2022-06-27 12:31 UTC
v.8.1.2 zip

![status](https://user-images.githubusercontent.com/13450219/175942215-accf4e22-a8ce-4d0c-9d72-8e80ba7dc7b1.png)

**Comment by f1-outsourcing** [comment] 2022-06-28 19:19
This way bugs are never fixed if you just close everything you did not check properly, why don't you open the correct page, your page is not even the same as mine. Afaik the Active value is default, it is just not show in the form, like user type is.

**Comment by pgorod** [comment] 2022-06-29 09:48
He does not open the correct page, and his page is not the same as yours, because you don't bother to fill in the "steps to reproduce", and he has a lot more work to do besides handling your excessive tickets here.

@johnM2401 I think we should just immediately close _every_ ticket that doesn't follow the template, after we have warned and asked the person to fill it. No point in prolonging this kind of interaction.

**Comment by f1-outsourcing** [comment] 2022-06-29 10:37
@johnM2401 

Some basic knowledge of suitecrm is to be expected for processing issues here. It is obvious from the screen capture what page it is. If the developers would have eyes they would see such basic issues.

Closing the issue does not solve the problem, or maybe we should create issue, disable error logging in suitecrm. Then we do not have any errors and bugs at all!!! All problems sovled!!

**Comment by serhiisamko091184** [comment] 2024-05-09 14:10
Hello @f1-outsourcing,

I'm afraid I can't replicate the issue using SuiteCRM version 8.1.2 or 8.6.0.
If this is still the case, I'd like to get more information on replication steps, please.    

Thanks! 

Regards,
Serhii

**Comment by f1-outsourcing** [comment] 2024-05-09 17:57
I am back on 7, can't tell you anything on 8

**Comment by serhiisamko091184** [comment] 2024-05-10 09:27
Hello @f1-outsourcing,

thanks for the quick reply, closing this one as I didn't manage to identify unexpected behaviour. 
Feel free to reopen this issue if we need to continue working on it. 

Thanks a lot! 

Regards,
Serhii

**Closed by serhiisamko091184** 2024-05-10 09:27 UTC
Labels: Area: Users
