### ISSUE TITLE
Suite Crm 2fa Blank Page Issue

### ISSUE THREAD

**Issue by Syedimran98** [salesagility/SuiteCRM-Core#483] opened 2024-05-15 07:00 UTC
I'm encountering a problem with Suite CRM's login functionality specifically when 2FA (Two-Factor Authentication) is enabled for users. I've noticed this issue manifesting in two different scenarios:

**Scenario 1:**
-----------------
When I enable 2FA for a user while logged in as an admin, the user is unable to log in, and an error message is displayed. Below is a screenshot illustrating this issue.

![MU249npB](https://github.com/salesagility/SuiteCRM-Core/assets/133844650/e52e8c91-92a2-4e61-887c-2c67167d032d)

**Scenario 2:**
-----------------
In this scenario, after entering the username and password on the login page, the system successfully redirects me to the 2FA interface page where I am prompted to enter the code received via email. However, the issue arises when I try to cancel or reload the page at this stage. Upon attempting to cancel or reload the page while on the 2FA interface, the page goes blank, and I am unable to proceed with the login process. Screenshots illustrating this behavior are provided below.

![zO7wi7D5](https://github.com/salesagility/SuiteCRM-Core/assets/133844650/6a845bda-3cbe-46a1-9a7f-9aacfeca32c7)

below I have attached recorded video of this issue..

https://github.com/salesagility/SuiteCRM-Core/assets/133844650/ff1b3c9f-ac3a-4666-90aa-dd15de726cc5

Thank you for your attention to this matter. Your feedback and suggestions are greatly appreciated. Looking forward to resolving this issue collaboratively and apologies for the oversight.

**Comment by scicali** [comment] 2024-05-15 07:13
2FA is expected in October 2024

https://suitecrm.com/suitecrm-roadmap/

**Comment by Syedimran98** [comment] 2024-05-15 07:47
Okay Thanks for quick reply.

**Comment by mattlorimer** [comment] 2024-12-05 11:24
Closed as duplicate of https://github.com/salesagility/SuiteCRM-Core/issues/52

**Closed by mattlorimer** 2024-12-05 11:24 UTC
Labels: Type: Bug, Type:Duplicate, Priority:Important, Type:Missing Feature, Severity: Moderate
