### ISSUE TITLE
Blank page on index.php load

### ISSUE THREAD

**Issue by trainingcity** [salesagility/SuiteCRM-Core#10] opened 2021-07-23 17:49 UTC
#### Issue
Followed beta install instructions on a fresh deb 10 vm. May have screwed something up during db setup.  In any case, getting a blank webpage on load.

#### Expected Behavior
Not sure, some sort of setup page?

#### Actual Behavior
 Blank page. page source follows

`

> <html>
> <body>
> 
> 
> <!DOCTYPE html>
> --
>   | <html lang="en">
>   |  
>   | <head>
>   | <meta charset="utf-8"/>
>   | <title>SuiteCRM</title>
>   | <base href=""/>
>   |  
>   | <meta http-equiv="cache-control" content="no-cache, must-revalidate, post-check=0, pre-check=0">
>   | <meta http-equiv="expires" content="0">
>   | <meta http-equiv="pragma" content="no-cache">
>   | <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1"/>
>   |  
>   | <link rel="manifest" href="site.webmanifest">
>   | <link rel="icon" type="image/x-icon" href="dist/themes/suite8/images/favicon.ico"/>
>   | </head>
>   |  
>   | <body>
>   | <app-root></app-root>
>   | <script src="dist/polyfills-es5.166ea56ffbe4182c0c7c.js" nomodule defer></script><script src="dist/polyfills-es2015.af170ffe981b0ba2d77d.js" type="module"></script><script src="dist/styles-es2015.016e215452bfa9ef2f89.js" type="module"></script><script src="dist/styles-es5.016e215452bfa9ef2f89.js" nomodule defer></script><script src="dist/main-es2015.16d9d4992b4627546ed8.js" type="module"></script><script src="dist/main-es5.16d9d4992b4627546ed8.js" nomodule defer></script></body>
>   | </html>
> 
> 
> </body>
> </html>``
> 

#### Your Environment
Chrome browser
server Deb 10 Apache.

**Comment by trainingcity** [comment] 2021-07-23 18:19
should mention I'm pointing apache virtual host to ./public. I noticed if I go to ./public/legacy/install.php I get a setup page?

**Comment by pgorod** [comment] 2021-07-24 15:38
Have you seen this list of known issues and fixes?

https://community.suitecrm.com/t/suitecrm-8-beta-install-questions/79383

I was able to install mine after going through a couple of those listed there.

**Comment by clemente-raposo** [comment] 2021-08-25 09:56
Hi @trainingcity,

Thanks for trying out SuiteCRM 8 Beta,

Are you still having this issue? Did the forum thread suggested by @pgorod  help?

**Comment by trainingcity** [comment] 2021-08-25 10:07
Thanks. I gave up. May revisit when 8 is GA. I am finding the significant and unknown costs associated with all the add on modules makes the entire project difficult to justify.

**Comment by clemente-raposo** [comment] 2021-08-25 10:12
Hi @trainingcity, understand. Thank you for the feedback.

**Comment by BryanXu77** [comment] 2021-11-24 03:50
I have got the same issue with SuiteCRM 8 GA release today, let me try to do the troubleshooting first.

**Comment by BryanXu77** [comment] 2021-11-24 07:00
I have fixed the blank page issue, the root cause is AllowOverride parameter was set to None by default.
1. Change /etc/httpd/conf/httpd.conf file, set AllowOverride as All for /var/www/html directory.
2. Restart apache.

**Comment by Mac-Rae** [comment] 2021-12-07 15:03
Closed as appears to be not required nad issue is raised in another report. Any further issues let us know!

**Closed** 2021-12-07 15:02 UTC
