### ISSUE TITLE
Dynamic Dropdowns dont appear to save

### ISSUE THREAD

**Issue by markbond1007** [salesagility/SuiteCRM-Core#381] opened 2023-11-07 15:53 UTC
#### Issue

Having set-up on a Bog standard Suite841 with a very basic Dynamic drop down (which does filter etc as it should). Selecting an option ensures it appears in the form box, however upon clicking Save its not saved, the graphql query shows the fields as blank. The parent dropdown saves fine.

#### Expected Behavior

The dynamic dropdown value should save to the DB

#### Actual Behavior

On saving the Dynamic Drop down value is blank

#### Steps to Reproduce

1. Add a parent dropdown (country) UK and US values.
2.Add a sub dropdown with counties (UK_Lincolnshire, UK_Essex, US_NewYork)
3.Add to a module (field country_c Dropdown country, field county_c drop down counties parent country_c)
4. Place on Detailview.
5. Edit an item in your module select UK then select Lincolnshire
6. Click Save
7. 

#### Your Environment

* SuiteCRM Version used: 8.4.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 119.0.6045.105 (Official Build) (x86_64)
* Environment name and version (e.g. MySQL, PHP 7): MySQL PHP8.1
* Operating System and version (e.g Ubuntu 16.04): Debian

**Comment by Ib-R** [comment] 2023-11-08 14:36
i have the same issue and also the Multiselect field needs to be refilled every time the record get edited

**Comment by yeu0thibao** [comment] 2023-11-15 11:20
i have the same issue

**Comment by gemartin21** [comment] 2023-11-30 10:29
https://github.com/salesagility/SuiteCRM-Core/pull/382

**Comment by Ib-R** [comment] 2024-01-30 16:07
Any update regarding this bug it's not even fixed in version 8.5 and it is critical.

**Comment by AlexMyddleware** [comment] 2024-02-26 06:17
I would like to propose a solution dynamic enum.

![image](https://github.com/salesagility/SuiteCRM-Core/assets/106162060/6101038a-1354-4aaa-9fc3-af27d9835475)

The problems comes from the fact that in src/core/app/core/src/lib/fields/base/base-enum.component.ts the value of the child dropdown gets emptied no matter what happens, even upon saving the record. With the filter that i included, the child value is only reset if the value of the parent dropdown changes or is emptied, thus working as intended.

**Comment by Ib-R** [comment] 2024-02-26 14:48
I tried adding this condition and it did work for me

**Comment by MaxSantolo** [comment] 2024-02-28 12:41
Not working for me on a 4 level Dynamic Dropdowns case

**Comment by AlexMyddleware** [comment] 2024-02-29 10:33
hey @MaxSantolo, can you explain what you mean by 4 level Dynamic Dropdowns case ? is it field D depending on Field C depending on field B depending on field A ? I would like to test your situation to add it to my fix, give me as much detail as you can so i can help you, thanks in advance

**Comment by AlexMyddleware** [comment] 2024-02-29 13:14
ok thanks @MaxSantolo i'll try to replicate that with random string values for the possible choices, feel free to share what your fields / dropdown lists / values to select are if it's not too confidential, it could help replicate

**Comment by MaxSantolo** [comment] 2024-03-01 10:47
Sorry can't disclosure but its something like one -> one_one -> one_one_specialty -> one_one_specialty_course

**Comment by AlexMyddleware** [comment] 2024-03-07 20:42
hey @MaxSantolo  i was able to get the four level running, look

![image](https://github.com/salesagility/SuiteCRM-Core/assets/106162060/9d6f7300-7799-411e-947a-6f86da3e9113)


![image](https://github.com/salesagility/SuiteCRM-Core/assets/106162060/e8d6ef06-1179-4c6c-bc76-a527a5b6bed6)

![image](https://github.com/salesagility/SuiteCRM-Core/assets/106162060/39f86453-b47e-4aa8-87f5-562f0099e323)


![image](https://github.com/salesagility/SuiteCRM-Core/assets/106162060/7ea19769-07fb-493e-9e09-9dba74d7c8eb)

it properly saved and it changes the values accordingly: it empty the field if i empty the parent, and if empty the top parrent then the 4 fields are emptied

maybe there is a tiny error in your lists ? for me at first the last field was empty because there was something wrong with the list values

**Comment by MaxSantolo** [comment] 2024-03-08 06:23
@AlexMyddleware  thank you I managed to solve the problem myself shortening the ids of the items. Your help was very precious, thanks a lot!

**Comment by johnM2401** [comment] 2024-04-11 09:19
Hey all!
Thank you for raising this @markbond1007, and thank you to everyone for your discussions/contributions!

I'm going to close this off as the issues with Dynamic Dropdowns should have now been resolved with the changes to Enum/Multi-Enum/Relate-type fields in the latest release (8.6.0)

See gif, showing Core and Custom Dynamic Dropdowns on Cases:
![dynamicDD](https://github.com/salesagility/SuiteCRM-Core/assets/13675281/7cb5ccb7-2b09-4cd2-a41f-6e7dbc0b7d61)

However, if you are still experiencing Dropdown / Dynamic Dropdown related issues on this release, please let us know and we can re-investigate.

Thanks folks!

**Closed by johnM2401** 2024-04-11 09:19 UTC
Labels: Type:Bug, Priority:Important, Status: Fix Proposed
