### ISSUE TITLE
Document Filenames Not Displaying in Subpanels

### ISSUE THREAD

**Issue by LikhithR14** [salesagility/SuiteCRM-Core#480] opened 2024-05-14 05:16 UTC
The filenames of documents are not displaying in subpanels under various modules such as opportunities etc. This issue persists across modules where documents should be listed. Upon investigation, it appears that the filename column remains blank in the subpanels, making it impossible to identify or download the associated documents directly from these subpanels.

#### Issue
 Document filenames not displaying in subpanels

#### Expected Behavior
Document filenames should be visible within subpanels under respective modules.
Users should be able to download documents by clicking on their filenames within the subpanels.

#### Actual Behavior
The filename column within subpanels remains blank, devoid of any document names.
Consequently, users are unable to identify or download documents directly from subpanels.

#### Steps to Reproduce
Access the demo environment.
Navigate to any module (e.g., Opportunity) related to Documents.
Click on the Document subpanel.
If no documents exist, create one.
Observe that the filename columns within the subpanel are blank, regardless of document creation.

Attachments (if applicable):
This issue seems to be comparable for version 7 
Attached Screenshots demonstrating the blank filename column in subpanels.
![SuiteCRM-V7](https://github.com/salesagility/SuiteCRM-Core/assets/145318179/ddbd2f22-3eee-4358-86a1-1267408a85f0)
![SuiteCRM-V8](https://github.com/salesagility/SuiteCRM-Core/assets/145318179/0d338db6-9c94-430f-b780-0ae0513fabe0)

#### Your Environment
SuiteCRM Version used: 8.6

**Comment by johnM2401** [comment] 2024-05-14 16:45
Hey!
Thank you for getting in touch and raising this!

As this appears to be a duplicate of the issue: https://github.com/salesagility/SuiteCRM-Core/issues/473

I'm going to close this off for now.

However, if you feel this is not a duplicate and should be dealt with as its own entity, please get back in touch and I'd be happy to re-investigate.

(Or if you notice any other issues within the CRM, please get in touch)

Thank you again!

**Closed by johnM2401** 2024-05-14 16:45 UTC
