### ISSUE TITLE
[REQ] Make DB _usdollar fields currency agnostic

### ISSUE THREAD

**Issue by rmendes-13** [salesagility/SuiteCRM-Core#407] opened 2023-12-05 14:27 UTC
## Context and Request

We've come across the realisation that there are currently 40 fields on the database named `_usdollar`.
I understand this makes a relation to what should be the US dollar currency, which logically for an American company would make sense as their base currency.

![Screenshot 2023-12-05 at 14 20 53](https://github.com/salesagility/SuiteCRM-Core/assets/149193091/45f3586a-d160-416c-9b36-2a68b4a316b5)

However on a global world, where I believe many current users, developers and SalesAgility itself are from Europe, but they could be from anywhere really, I don't think keeping a reference to `_usdollar` is correct.

Instead all fields and code could benefit from a simple update replacing the `_usdollar` with `_base` or `_basecur` or whatever, which is currency agnostic, and serves all purposes for what its intended. Even with `sed` it could be quickly and easily done.

Also, during an update a script could take care of the database,

```
ALTER TABLE table_name;
RENAME COLUMN oldColumn TO newColumn;
```

**Comment by rmendes-13** [comment] 2023-12-05 18:45
Hi @pgorod and thank you for your opportunity to comment.

I understand what you're saying, however I believe your description does not match the application behaviour.

When the user first runs the `install.php` script and configures locale, one sets the base currency of preference. Default is USD but you can simply scratch that and type in the ISO code EUR and the currency symbol €.
Base conversion rate is 1 because the base currency is EUR. This is my actual situation, and how the initial config went.

So if I check the currencies table, returns empty, as there's only one currency:
```
mysql> select * from currencies;
Empty set (0.03 sec)
```

and checking the SuiteCRM generated configuration file:
```
# cat public/legacy/config.php | grep default_currency
  'default_currency_iso4217' => 'EUR',
  'default_currency_name' => 'Euro',
  'default_currency_significant_digits' => '2',
  'default_currency_symbol' => '€',
```
So this is the base currency. There is no other.

Now let's see how this is put to action by taking information from quote on the aos_quotes table:
```
mysql> select currency_id,total_amt,total_amt_usdollar,total_amount,total_amount_usdollar from aos_quotes;
+-------------+------------+--------------------+--------------+-----------------------+
| currency_id | total_amt  | total_amt_usdollar | total_amount | total_amount_usdollar |
+-------------+------------+--------------------+--------------+-----------------------+
| -99         | 645.000000 |         645.000000 |   793.350000 |            793.350000 |
+-------------+------------+--------------------+--------------+-----------------------+
1 row in set (0.03 sec)
```

But ... I have no US dollars.

So in the end, the actual behaviour (and correct from where I'm standing) is that config asks for the base currency, is set, and SuiteCRM identifies that currency as the base currency.
Only the database fields are named wrong.
I am not a developer as you know but I believe the fix here is very very simple: just replace all occurrences of `_usdollar` with whatever the new termination should be, (this is fairly easy to achieve using `sed`), and also the rename of the column is possible within the database.

**Comment by pgorod** [comment] 2023-12-05 19:46
I still think the installer is defining a **default** currency for new users, not a **base** currency that will serve as the common unit for DB-stored values.

I just tried adding a currency called "doubles" with conversion rate at `2` and confirmed that when I save a quote with a value of `33`, the DB shows dollar amounts as `16.5`. 

In reality, you are right that the field names mention dollars unnecessarily, but how is that a problem? People don't usually go around peeking in the database. 

On the other side of the equation are the costs of changing it: and I see [too many references to it in the code](https://github.com/search?q=repo%3Asalesagility%2FSuiteCRM-Core+_usdollar&type=code&p=2). Some of them in string calculations to build up field names from parts. With my experience of this project, I would say it is too risky to change this.

It would needlessly pollute the git tree with changes that bring headaches to people trying to manage their own forked repositories, their own customizations. There would be a lot of merging going on around the world, too much for something just intended to tidy up the field names.

Also, I wouldn't trust the post install scripts changing DB structure not to bring troubles too. The general level of the SuiteCRM sysadmin is sometimes scary. People jump on the software because it's free, not because they're ready to operate it properly. Upgrades get interrupted half-way through and there are no backups, they just have to patch their way forward.... We see it on the Forums frequently. Unfortunately.

And many people install or upgrade from git, and simply miss out on the scripts.

I could go on, but I really should just shut up now. This is just my humble opinion and I encourage others to chime in and speak their mind on this suggestion.

**Comment by rmendes-13** [comment] 2023-12-06 10:03
Hi there and once again thank you for the opportunity for comment.

About the "doubles" conversion, well, if you have a base currency, or system currency, or default, or however we wanna call it, and add a currency with a 2x conversion factor, obviously the DB will show, on the field for the default/system/base currency, 16.5.
Because 16.5 is the conversion rate to the base currency, not to US dollars.

Another place where you can clearly see this is, when anyone making a template goes to add the system currency, you get a variable "_usdollar".
![Screenshot 2023-12-06 at 09 54 41](https://github.com/salesagility/SuiteCRM-Core/assets/149193091/ba7e89f2-96ef-4975-bbf7-2fa8820b2fb7)
So people DO SEE the field names. 

About the fix, I am struggling to understand your point ... post install scripts don't work? Database queries don't work??
Post install scripts are ran everywhere and anywhere, most apps managed via package repo have post install scripts, are you implying they are no good? Having some trouble to figure this one out.

From the link you've presented, I see only 60 files, I didn't see any "string calculations" (but I could have missed some), all I see are either `_usdollar` or `_USDOLLAR`. and `sed` can be case insensitive so it would be very possible to replace that text alone, cleanly.

I'm looking into simplifying, you keep adding complications that don't exist. Post install scripts don't work, string calculations (?), queries don't work ... don't get it.

**Comment by pgorod** [comment] 2023-12-06 17:17
I guess I'm an old grumpy skeptic after 57k posts read on the Forums, and 17k written trying to help. I've seem so much mess. I would not create a PR with 60 touched files, made from an automatic replace, because I think it's too risky with such a flaky software. But anyone can do it, and I have zero authority over what gets merged here, so...

Git works. What doesn't work so well is managing git for your own developments, in a project that has over 400 unmerged PR's. Many of those are problems I need solved, so I have my own changes to files, including core files. That's why the upgrade of my dev machine from v8.4.1 to v8.4.2 took me some 8h of work last week. It was a headache and involved a lot of tedious going through manual merge of dozens of files. Some of this mess was caused by my own mistakes in the process, admittedly. But it's hard not to make mistakes when things get complex.

So, to me, the less is changed in core, the better. Or to phrase it more accurately - I want merges that touch a few files for the maximum benefit, instead of touching many files for a small benefit.

**Comment by mattlorimer** [comment] 2023-12-06 17:32
@rmendes-13 Thank you for suggestion, we completely understand your point here, but this is something we will likely tackle till further down the line when do more of a major shift in the platform and database, for now the benefit is quite small and is more likely to cause upgrade issues or other issues etc with customisation.

**Closed by mattlorimer** 2023-12-06 17:32 UTC
