### ISSUE TITLE
Filtering null values

### ISSUE THREAD

**Issue by Kevconry** [salesagility/SuiteCRM-Core#216] opened 2023-02-14 13:07 UTC
#### Issue
When on the Campaign listview, trying to filter, with null values, causes them to show when they shouldnt

#### Expected Behavior
Null values shouldn't show when filtering

#### Actual Behavior
Null values, show when filtering

#### Steps to Reproduce

1. Go to campaigns
2. Create 3 different types of campaigns but leave "End date" empty. To do this, when you give the campaign a title, click on the campaign dropdown, and click "View Campaigns"
3. Attempt to filter for a campaign that equals a certain day

#### Your Environment

* SuiteCRM Version used: 8.2.3
* Browser name and version: Version 110.0.5481.77 (Official Build) (64-bit)
* Environment name and version: MYSQL, PHP8.1
* Operating System and version: Ubuntu 22.04.1 LTS

**Comment by scicali** [comment] 2023-02-14 13:12
duplicate of #92

**Closed** 2023-04-14 14:59 UTC
Labels: Type:Bug, Priority:Moderate, Area: PHP8, Status: Team Investigating, Area: Backend
