### ISSUE TITLE
8.2.3 - No link to see emails in Email module

### ISSUE THREAD

**Issue by pabaillon** [salesagility/SuiteCRM-Core#206] opened 2023-02-01 09:25 UTC
#### Issue
In the email module, I can't read emails because there is no link to click .

#### Expected Behavior

I can click on email title to read it.

#### Actual Behavior

I have the list of emails without link.
#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 8.2.3
* PHP 7.4

**Comment by johnM2401** [comment] 2023-02-01 10:01
Hey @pabaillon 

Could you provide more information on this?

ie:

Steps to replicate
Screenshots of what you see
Any errors in Browser Console / Suitecrm.log / php logs
What type of Email Account you used. (basic auth / Oauth2)
Email service used (MS365/Gmail/etc)

Looks like this could possible be a duplicate of: https://github.com/salesagility/SuiteCRM/issues/9921

But I'd like some more information, to try to narrow this down.

Thanks!

**Comment by IgorA100** [comment] 2023-02-11 08:09
I have a completely similar problem after upgrading from 8.2.0 to 8.2.3. All modules work fine except Emails
Screenshot attached. There are no errors in the browser now. BUT! Yesterday there was a 500 error when accessing <My Site>/legacy/index.php?module=Emails and the list of emails was not displayed at all. Today the error itself disappeared, in a standard way. Although I cleared the cache several times yesterday, rebooted the services and the server itself.
![BugEmail](https://user-images.githubusercontent.com/5006170/218247692-87110259-36b5-4f4d-a4ec-5839aa6bb954.jpg)
This is NOT a duplicate of https://github.com/salesagility/SuiteCRM/issues/99211

**Comment by johnM2401** [comment] 2023-02-16 10:24
Hey folks

Thanks for getting in touch

I'm able to replicate this issue now, and will mark it as a bug.

Thank you for raising!

**Closed** 2023-02-23 17:40 UTC
Labels: Type:Bug, Priority:Important, Area: Emails
